In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data"

columns = [
    "age","workclass","fnlwgt","education","education-num",
    "marital-status","occupation","relationship","race","sex",
    "capital-gain","capital-loss","hours-per-week","native-country","income"
]

df = pd.read_csv(url, names=columns)

print(type(df))   # Should be pandas DataFrame

df.to_csv("D:/spp/adult/adult.csv")

<class 'pandas.DataFrame'>

<h2>Prediction task is to determine whether a person's income is over $50,000 a year.</h2>

In [2]:
df.dtypes

age               int64
workclass           str
fnlwgt            int64
education           str
education-num     int64
marital-status      str
occupation          str
relationship        str
race                str
sex                 str
capital-gain      int64
capital-loss      int64
hours-per-week    int64
native-country      str
income              str
dtype: object

| Variable Name  | Role    | Type        | Demographic     | Description / Categories                                                                                      | Missing Values |
| -------------- | ------- | ----------- | --------------- | ------------------------------------------------------------------------------------------------------------- | -------------- |
| age            | Feature | Integer     | Age             | Age in years                                                                                                  | No             |
| workclass      | Feature | Categorical | Income          | Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked         | Yes            |
| fnlwgt         | Feature | Integer     | —               | Final sample weight                                                                                           | No             |
| education      | Feature | Categorical | Education Level | Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th–Preschool, Masters, Doctorate | No             |
| education-num  | Feature | Integer     | Education Level | Numeric education level                                                                                       | No             |
| marital-status | Feature | Categorical | Other           | Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse     | No             |
| occupation     | Feature | Categorical | Other           | Tech-support, Craft-repair, Sales, Exec-managerial, Prof-specialty, etc.                                      | Yes            |
| relationship   | Feature | Categorical | Other           | Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried                                            | No             |
| race           | Feature | Categorical | Race            | White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black                                                   | No             |
| sex            | Feature | Binary      | Sex             | Female, Male                                                                                                  | No             |
| capital-gain   | Feature | Integer     | —               | Capital gains amount                                                                                          | No             |
| capital-loss   | Feature | Integer     | —               | Capital losses amount                                                                                         | No             |
| hours-per-week | Feature | Integer     | —               | Weekly working hours                                                                                          | No             |
| native-country | Feature | Categorical | Other           | United-States, India, Mexico, etc.                                                                            | Yes            |
| income         | Target  | Binary      | Income          | >50K, <=50K                                                                                                   | No             |

In [3]:
df.dtypes

age               int64
workclass           str
fnlwgt            int64
education           str
education-num     int64
marital-status      str
occupation          str
relationship        str
race                str
sex                 str
capital-gain      int64
capital-loss      int64
hours-per-week    int64
native-country      str
income              str
dtype: object

In [4]:
df.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
hours-per-week    0
native-country    0
income            0
dtype: int64

In [5]:
obj_cols=df.select_dtypes(include=['string','object'])
obj_cols

,workclass,education,marital-status,occupation,relationship,race,sex,native-country,income
0,State-gov,Bachelors,Never-married,Adm-clerical,Not-in-family,White,Male,United-States,<=50K
1,Self-emp-not-inc,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,United-States,<=50K
2,Private,HS-grad,Divorced,Handlers-cleaners,Not-in-family,White,Male,United-States,<=50K
3,Private,11th,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,United-States,<=50K
4,Private,Bachelors,Married-civ-spouse,Prof-specialty,Wife,Black,Female,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...
32556,Private,Assoc-acdm,Married-civ-spouse,Tech-support,Wife,White,Female,United-States,<=50K
32557,Private,HS-grad,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,United-States,>50K
32558,Private,HS-grad,Widowed,Adm-clerical,Unmarried,White,Female,United-States,<=50K
32559,Private,HS-grad,Never-married,Adm-clerical,Own-child,White,Male,United-States,<=50K
32560,Self-emp-inc,HS-grad,Married-civ-spouse,Exec-managerial,Wife,White,Female,United-States,>50K

In [6]:
obj_cols=obj_cols.drop(columns='income') # income is the target columns
obj_cols

,workclass,education,marital-status,occupation,relationship,race,sex,native-country
0,State-gov,Bachelors,Never-married,Adm-clerical,Not-in-family,White,Male,United-States
1,Self-emp-not-inc,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,United-States
2,Private,HS-grad,Divorced,Handlers-cleaners,Not-in-family,White,Male,United-States
3,Private,11th,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,United-States
4,Private,Bachelors,Married-civ-spouse,Prof-specialty,Wife,Black,Female,Cuba
...,...,...,...,...,...,...,...,...
32556,Private,Assoc-acdm,Married-civ-spouse,Tech-support,Wife,White,Female,United-States
32557,Private,HS-grad,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,United-States
32558,Private,HS-grad,Widowed,Adm-clerical,Unmarried,White,Female,United-States
32559,Private,HS-grad,Never-married,Adm-clerical,Own-child,White,Male,United-States
32560,Self-emp-inc,HS-grad,Married-civ-spouse,Exec-managerial,Wife,White,Female,United-States

In [7]:
df["income"] = df["income"].str.strip()
df["income"] = df["income"].map({"<=50K": 0, ">50K": 1})

In [8]:
df["income"]

0        0
1        0
2        0
3        0
4        0
        ..
32556    0
32557    1
32558    0
32559    0
32560    1
Name: income, Length: 32561, dtype: int64

In [9]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for i in obj_cols:
    df[i]=le.fit_transform(df[i])

In [10]:
obj_cols

,workclass,education,marital-status,occupation,relationship,race,sex,native-country
0,State-gov,Bachelors,Never-married,Adm-clerical,Not-in-family,White,Male,United-States
1,Self-emp-not-inc,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,United-States
2,Private,HS-grad,Divorced,Handlers-cleaners,Not-in-family,White,Male,United-States
3,Private,11th,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,United-States
4,Private,Bachelors,Married-civ-spouse,Prof-specialty,Wife,Black,Female,Cuba
...,...,...,...,...,...,...,...,...
32556,Private,Assoc-acdm,Married-civ-spouse,Tech-support,Wife,White,Female,United-States
32557,Private,HS-grad,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,United-States
32558,Private,HS-grad,Widowed,Adm-clerical,Unmarried,White,Female,United-States
32559,Private,HS-grad,Never-married,Adm-clerical,Own-child,White,Male,United-States
32560,Self-emp-inc,HS-grad,Married-civ-spouse,Exec-managerial,Wife,White,Female,United-States

In [11]:
df

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,7,77516,9,13,4,1,1,4,1,2174,0,40,39,0
1,50,6,83311,9,13,2,4,0,4,1,0,0,13,39,0
2,38,4,215646,11,9,0,6,1,4,1,0,0,40,39,0
3,53,4,234721,1,7,2,6,0,2,1,0,0,40,39,0
4,28,4,338409,9,13,2,10,5,2,0,0,0,40,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,4,257302,7,12,2,13,5,4,0,0,0,38,39,0
32557,40,4,154374,11,9,2,7,0,4,1,0,0,40,39,1
32558,58,4,151910,11,9,6,1,4,4,0,0,0,40,39,0
32559,22,4,201490,11,9,4,1,3,4,1,0,0,20,39,0
32560,52,5,287927,11,9,2,4,5,4,0,15024,0,40,39,1

<H5> FOR CLASSIFICATION PROBLEM NO NEED FOR CORRELAITON MATRIX</H5>

In [12]:
import matplotlib.pyplot as plt
import seaborn as sns

In [13]:
X=df.drop(columns='income')
y=df['income']

In [14]:
X.shape,y.shape

((32561, 14), (32561,))

In [15]:
from sklearn.model_selection import train_test_split
Xtrain,Xtest,ytrain,ytest=train_test_split(X,y,test_size=0.2,random_state=42)

<h3> LOGISTIC REGRESSION</H3>

In [16]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()

In [17]:
lr.fit(Xtrain,ytrain)

LogisticRegression()

In [18]:
ypred=lr.predict(Xtest)

In [19]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(lr, X, y, cv=5, scoring='accuracy')
scores

array([0.78734838, 0.78854423, 0.7845516 , 0.78439803, 0.7906941 ])

In [20]:
from sklearn.metrics import *
print("Test Accuracy:", accuracy_score(ytest, ypred))
print("Classification Report",classification_report(ytest, ypred))
print("Confustion matrix\n", confusion_matrix(ytest,ypred))

Test Accuracy: 0.7899585444495624
Classification Report               precision    recall  f1-score   support

           0       0.81      0.94      0.87      4942
           1       0.64      0.30      0.41      1571

    accuracy                           0.79      6513
   macro avg       0.72      0.62      0.64      6513
weighted avg       0.77      0.79      0.76      6513

Confustion matrix
 [[4670  272]
 [1096  475]]

In [21]:
from sklearn.model_selection import train_test_split, GridSearchCV
param_grid = {
    'C': [1000,1500,2000],
    'penalty': ['l1','l2','elasticnet'],          
    'solver': ['lbfgs','saga','sag','liblinear']        
}

grid = GridSearchCV(lr, param_grid, cv=5, scoring='accuracy')
grid.fit(Xtrain, ytrain)

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1000, 1500, 2000],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['lbfgs', 'saga', 'sag', 'liblinear']},
             scoring='accuracy')

In [22]:
grid.best_params_

{'C': 2000, 'penalty': 'l1', 'solver': 'liblinear'}

In [23]:
ypred=grid.predict(Xtest)

In [24]:
scores = cross_val_score(grid, X, y, cv=5, scoring='accuracy')
scores

array([0.8208199 , 0.82263514, 0.82340295, 0.82493857, 0.82724201])

In [25]:
print("Test Accuracy:", accuracy_score(ytest, ypred))
print("Classification Report",classification_report(ytest, ypred))
print("Confustion matrix\n", confusion_matrix(ytest,ypred))

Test Accuracy: 0.8258866881621373
Classification Report               precision    recall  f1-score   support

           0       0.84      0.95      0.89      4942
           1       0.72      0.45      0.55      1571

    accuracy                           0.83      6513
   macro avg       0.78      0.70      0.72      6513
weighted avg       0.81      0.83      0.81      6513

Confustion matrix
 [[4674  268]
 [ 866  705]]

<h2>RandomForest</h2>

In [26]:
from sklearn.ensemble import RandomForestClassifier

In [27]:
rf=RandomForestClassifier(oob_score=True)

In [28]:
rf.fit(Xtrain,ytrain)

RandomForestClassifier(oob_score=True)

In [29]:
rf.predict(Xtest)

array([0, 0, 1, ..., 1, 0, 0], shape=(6513,))

In [30]:
scores = cross_val_score(rf, X, y, cv=5, scoring='accuracy')
scores

array([0.85413788, 0.85288698, 0.85826167, 0.86056511, 0.85595823])

In [31]:
oob_error = 1 - rf.oob_score
oob_error

0

In [32]:
print("Test Accuracy:", accuracy_score(ytest, ypred))
print("Classification Report",classification_report(ytest, ypred))
print("Confustion matrix\n", confusion_matrix(ytest,ypred))

Test Accuracy: 0.8258866881621373
Classification Report               precision    recall  f1-score   support

           0       0.84      0.95      0.89      4942
           1       0.72      0.45      0.55      1571

    accuracy                           0.83      6513
   macro avg       0.78      0.70      0.72      6513
weighted avg       0.81      0.83      0.81      6513

Confustion matrix
 [[4674  268]
 [ 866  705]]

In [33]:
param_grid={
    'n_estimators':[10,20,100,500,1000],
    'criterion':['gini', 'entropy', 'log_loss'],
    #'splitter':['best', 'random'], only for dt
    'max_depth':[10,20,30,40,50],
    'random_state':[0,2,3,4]    
}

In [34]:
grid = GridSearchCV(rf, param_grid, cv=5, scoring='accuracy')

In [ ]:
grid.fit(Xtrain, ytrain)

In [ ]:
grid.best_params_

In [ ]:
print("Test Accuracy:", accuracy_score(ytest, ypred))
print("Classification Report",classification_report(ytest, ypred))
print("Confustion matrix\n", confusion_matrix(ytest,ypred))